spring:
  application:
    name: fitmeasure
  profiles:
    default: local
  thymeleaf:
    cache: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:fitmeasure;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true